<?php if(basename($_SERVER['PHP_SELF']) == basename(__FILE__)) { header('Location: blog.php?pg='.substr(basename(__FILE__), 3, -4)); die(); }
if(!isset($com_titulo) || $com_titulo != false) {
	echo "			<h2>O Autor</h2>\n";
	echo '			<img src="divider.gif" width="545" height="3" border="0" alt="" align="center" /><br />'."\n";
	echo "			<br />";
}
?>
<img src="claudio_villa.jpg" <? $size = getimagesize('claudio_villa.jpg'); echo $size[3]; ?> border="0" alt="Claudio Villa" align="left" vspace="3" hspace="10" />
<p>Nasci em S&atilde;o Paulo em 1979 e desde cedo j&aacute; era atra&iacute;do pela leitura e pela escrita. Eu sempre adorei as aulas de reda&ccedil;&atilde;o na escola e sempre usava o “tema livre” para escrever algum tipo de hist&oacute;ria. Meu quarto sempre foi a biblioteca da casa e me lembro de passar in&uacute;meras tardes lendo e devorando todo tipo de material, dos livros infantis &agrave;s p&aacute;ginas da enciclop&eacute;dia Conhecer.</p>
<p>N&atilde;o consigo precisar exatamente quando comecei a ter gosto pelas hist&oacute;rias de capa e espada, mas lembro de alguns epis&oacute;dios que podem dar uma boa pista sobre isso. A escola de meu pai possu&iacute;a uma marcenaria totalmente equipada (o pr&eacute;dio fora uma marcenaria no passado) e como meu pai sempre gostou muito de mexer com madeira, eu me lembro de dois presentes que ele me deu e que me marcaram muito. </p>
<p>O primeiro veio quando eu tinha por volta de seis a sete anos e era, como eu o chamava na &eacute;poca, um “barco que cabia gente”. O tal barco feito por ele nada mais era que uma caixa de madeira, com laterais de pano e que possu&iacute;a um banco, um tim&atilde;o, uma pequena ancora de madeira e um &uacute;nico mastro com uma vela de pano que podia ser erguida. Lembro-me de passar muitas tardes viajando por oceanos fant&aacute;sticos a bordo daquele pequeno navio em meu quarto. O segundo presente (eu devia ter uns dez anos nessa &eacute;poca) foi uma simples espada de madeira com a qual enfrentei os primeiros monstros imagin&aacute;rios da minha vida.</p>
<p>O tempo passou, eu cresci e j&aacute; mais velho acompanhei por muitas noites enquanto meu pai, sentado em sua bancada de madeira, montava modelos em escala dos mais variados navios a vela j&aacute; existentes. Eu ficava admirado vendo-o fabricar cada pe&ccedil;a, cada cordaime, cada peda&ccedil;o de madeira e daqueles dias em diante passei a achar essas embarca&ccedil;&otilde;es uma das mais belas cria&ccedil;&otilde;es feitas pelas m&atilde;os do homem.</p>
<p>Como j&aacute; disse l&aacute; em cima, eu sempre gostei muito de escrever, sendo que muito da minha produ&ccedil;&atilde;o adolescente consistia de pequenas poesias e versos ou textos aleat&oacute;rios que escrevia em noites insones. Minha primeira tentativa de escrever um livro foi aos quinze anos quando comecei a rascunhar algo na &uacute;ltima p&aacute;gina de um caderno da escola. Essas primeiras frases terminaram em um livro com aproximadamente cem p&aacute;ginas, que apesar de interessante, ainda n&atilde;o possu&iacute;a a maturidade que sinto ter hoje. </p>
<p>Na mesma &eacute;poca conheci aqueles que se tornariam meus melhores amigos e que juntos haviam criado um mundo imagin&aacute;rio de fantasia. Esse mundo tinha o prop&oacute;sito de servir de cen&aacute;rio para seus jogos de RPG, mas num futuro muito pr&oacute;ximo passaria a abrigar minhas hist&oacute;rias. </p>
<p>Ao longo dos seis anos seguintes, fui desenvolvendo lentamente o reino onde se passaria meu primeiro livro. Pouco a pouco eu criei uma cronologia, personagens chaves, bras&otilde;es e bandeiras, sua cultura e cren&ccedil;as e por fim um mapa onde colocar tudo isso. Logo eu tinha em minhas m&atilde;os um mundo veross&iacute;mil e habit&aacute;vel (ao menos para mim) mesmo sem saber exatamente o que fazer com ele.</p>
<p>Tudo come&ccedil;ou a mudar no final de 2000, quando conheci o pessoal do Graal Live Action e comecei a jogar suas aventuras. Eu precisava criar um personagem para jogar suas partidas e mesmo sem saber exatamente como ele seria, eu criei um alter ego que batizei de Jonathan Devilla. Os meses e jogos foram passando e pouco a pouco este que era apenas um nome passou a ter uma hist&oacute;ria, um passado e uma motiva&ccedil;&atilde;o. Outros personagens foram contribuindo para enriquecer seu perfil e a medida que  conquistava o respeito entre meus pares no jogo, passei mais e mais a gostar de vivenciar esse personagem. Um dia resolvi que iria tentar novamente escrever um livro e que o protagonista dessa hist&oacute;ria seria esse personagem. </p>
<p>Quatro anos se passaram a partir daquele dia. Muitos meses de noites mal dormidas, de devaneios em &ocirc;nibus e metr&ocirc;, de id&eacute;ias em uma noite quente e seca de Florian&oacute;polis. In&uacute;meras foram as vezes onde tive de correr (mesmo no meio da madrugada) at&eacute; um papel e um l&aacute;pis para registrar uma id&eacute;ia antes que ela fugisse de mim at&eacute; chegar no resultado de hoje, meu primeiro livro. </p>
<p>Sempre abominei a arrog&acirc;ncia e a futilidade, t&atilde;o presentes no mundo de hoje e por isso digo que escrever um livro est&aacute; longe de ser uma busca pessoal por fama e fortuna. Escrever “Pelo Sangue e Pela F&eacute;” foi antes de tudo vivenciar uma grande aventura, conhecer personagens de quem sinto falta e que se foram como amigos que embarcam em uma longa viagem. </p>
<p>Ao mesmo tempo em que as semanas passam e eu luto para conseguir realizar esse sonho, eu vivencio outra aventura pessoal, na companhia de outros personagens (alguns conhecidos) que me levam em suas aventuras pelo mundo da fantasia. Espero que possam compartilhar dessas viagens em breve, pois enquanto puder manejar uma pena, n&atilde;o deixarei de viver essas aventuras. </p>
<p>Para me contatar com suas duvidas, criticas e sugestões, o endereço é <a href="mailto:contato@mundosdemirr.com">contato@mundosdemirr.com</a>.</p>